#' Parse MEGAN Output Files
#'
#' This function parses MEGAN output files, typically in XML format, for taxonomic and functional data.
#'
#' @param file_path A string containing the path to the MEGAN output file (XML format).
#' @return A data frame with parsed taxonomic data, including taxonomic names and counts.
#' @details The function reads an XML file generated by MEGAN, extracts taxonomic assignments,
#' and summarizes the counts for each taxonomic rank.
#' @importFrom xml2 read_xml xml_find_all xml_text
#' @importFrom dplyr group_by summarise
#' @export
parse_megan <- function(file_path) {
  # Validate the file path
  if (!file.exists(file_path)) {
    stop("The specified MEGAN file does not exist.")
  }

  # Read the MEGAN XML file
  library(xml2)
  xml_data <- read_xml(file_path)

  # Extract taxonomic data (example assumes a specific XML structure)
  taxonomy_nodes <- xml_find_all(xml_data, "//taxonomy")
  taxonomy <- xml_text(taxonomy_nodes)

  count_nodes <- xml_find_all(xml_data, "//count")
  counts <- as.numeric(xml_text(count_nodes))

  # Check if lengths match
  if (length(taxonomy) != length(counts)) {
    stop("Mismatch between taxonomy entries and counts in the MEGAN file.")
  }

  # Create a data frame
  data <- data.frame(
    Taxonomy = taxonomy,
    Count = counts,
    stringsAsFactors = FALSE
  )

  # Summarize counts by taxonomy
  library(dplyr)
  parsed_data <- data %>%
    group_by(Taxonomy) %>%
    summarise(TotalCount = sum(Count), .groups = "drop")

  return(parsed_data)
}
