#' Parse MEGAN Output Files and Create a Phyloseq Object
#'
#' This function parses MEGAN output files, typically in XML format, for taxonomic and functional data.
#' It can create a `phyloseq` object for downstream analysis.
#'
#' @param file_path A string containing the path to the MEGAN output file (XML format).
#' @param to_phyloseq Logical. If `TRUE`, converts the parsed data into a `phyloseq` object. Default is `FALSE`.
#' @return A data frame with parsed taxonomic data or a `phyloseq` object if `to_phyloseq = TRUE`.
#' @details The function reads an XML file generated by MEGAN, extracts taxonomic assignments,
#' and summarizes the counts for each taxonomic rank. Optionally, it can create a `phyloseq` object.
#' @importFrom xml2 read_xml xml_find_all xml_text
#' @import dplyr
#' @import phyloseq
#' @export

parse_megan <- function(file_path, to_phyloseq = FALSE) {
  # Validate the file path
  if (!file.exists(file_path)) {
    stop("The specified MEGAN file does not exist.")
  }

  # Read the MEGAN XML file
  library(xml2)
  xml_data <- tryCatch({
    read_xml(file_path)
  }, error = function(e) {
    stop("Error reading the XML file. Ensure the file is valid XML.")
  })

  # Extract taxonomic data
  taxonomy_nodes <- xml_find_all(xml_data, "//taxonomy")
  taxonomy <- xml_text(taxonomy_nodes)

  # Extract counts
  count_nodes <- xml_find_all(xml_data, "//count")
  counts <- as.numeric(xml_text(count_nodes))

  # Check for mismatches in data length
  if (length(taxonomy) != length(counts)) {
    stop("Mismatch between taxonomy entries and counts in the MEGAN file.")
  }

  # Create a data frame
  data <- data.frame(
    Taxonomy = taxonomy,
    Count = counts,
    stringsAsFactors = FALSE
  )

  # Summarize counts by taxonomy
  library(dplyr)
  summarized_data <- data %>%
    group_by(Taxonomy) %>%
    summarise(TotalCount = sum(Count, na.rm = TRUE), .groups = "drop")

  # Return summarized data if `to_phyloseq` is FALSE
  if (!to_phyloseq) {
    return(summarized_data)
  }

  # Convert to phyloseq object
  library(phyloseq)
  otu <- otu_table(as.matrix(summarized_data$TotalCount), taxa_are_rows = TRUE)
  taxa <- tax_table(as.matrix(data.frame(Taxonomy = summarized_data$Taxonomy, row.names = summarized_data$Taxonomy)))
  samples <- sample_data(data.frame(Sample = "MEGAN_Output", row.names = "MEGAN_Output"))

  phyloseq_object <- phyloseq(otu, taxa, samples)

  return(phyloseq_object)
}
